// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Services;

#nullable disable

namespace Services.Migrations
{
    [DbContext(typeof(GeoConnectContext))]
    partial class GeoConnectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.AccionLugar", b =>
                {
                    b.Property<int>("IdAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccion"));

                    b.Property<DateTime?>("FechaAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaAccion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("googlePlaceId");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipoAccion");

                    b.HasKey("IdAccion")
                        .HasName("PK__LugaresA__E0B207A4DF513223");

                    b.HasIndex("GooglePlaceId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LugaresAcciones", (string)null);
                });

            modelBuilder.Entity("Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idComentario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int")
                        .HasColumnName("calificacion");

                    b.Property<string>("Comentario1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comentario");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaPublicacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("googlePlaceId");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.HasKey("IdComentario")
                        .HasName("PK__Comentar__C74515DA092105FE");

                    b.HasIndex("GooglePlaceId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("Models.Lugar", b =>
                {
                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("googlePlaceId");

                    b.Property<Geometry>("Coordenadas")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("coordenadas");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fotoUrl");

                    b.Property<int?>("IdMunicipio")
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    b.Property<string>("NombreLugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombreLugar");

                    b.HasKey("GooglePlaceId")
                        .HasName("PK__Lugares__FD6A056AB8A76094");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("Lugares", (string)null);
                });

            modelBuilder.Entity("Models.Municipio", b =>
                {
                    b.Property<int>("IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMunicipio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMunicipio"));

                    b.Property<string>("Departamento")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Antioquia")
                        .HasColumnName("departamento");

                    b.Property<string>("NombreMunicipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreMunicipio");

                    b.HasKey("IdMunicipio")
                        .HasName("PK__Municipi__FD10E400375E83FA");

                    b.ToTable("Municipios", (string)null);
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("TokenExpira")
                        .HasColumnType("datetime")
                        .HasColumnName("tokenExpira");

                    b.Property<string>("TokenVerificacion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tokenVerificacion");

                    b.Property<bool?>("Verificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("verificado");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__645723A627F384E6");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuarios__2A586E0B854D0267")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Models.AccionLugar", b =>
                {
                    b.HasOne("Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("GooglePlaceId")
                        .HasConstraintName("FK__LugaresAc__googl__5629CD9C");

                    b.HasOne("Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__LugaresAc__idUsu__5535A963");

                    b.Navigation("Lugar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.Comentario", b =>
                {
                    b.HasOne("Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("GooglePlaceId")
                        .HasConstraintName("FK__Comentari__googl__5BE2A6F2");

                    b.HasOne("Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Comentari__idUsu__5AEE82B9");

                    b.Navigation("Lugar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.Lugar", b =>
                {
                    b.HasOne("Models.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .HasConstraintName("FK__Lugares__idMunic__5165187F");

                    b.Navigation("Municipio");
                });
#pragma warning restore 612, 618
        }
    }
}
